### ISSUE TITLE
Add ExerciseWrapper and replace Exercise with it in Rwes

### ISSUE THREAD

**Issue by noahjutz** [noahjutz/GymRoutines#9]
### `ExerciseWrapper` class
This class will replace the `Exercise` class in `RoutineWithExercises` objects. It has a one-to-one relationship with an `Exercise` object. It will look something like this in `Domain`.
```kotlin
@Entity
data class ExerciseWrapper(
  val exerciseId: Int
)
```

### Todo list
- [ ] Add `ExerciseWrapper`to model
  - [x] Add the `ExerciseWrapper` class to `Domain.kt`
  - [x] Add `ExerciseWrapperDao`
  - [x] Add `Repository` funs
- [ ] Replace `Exercise` with `ExerciseWrapper` where relevant
